### ISSUE TITLE
Add licence file

### ISSUE THREAD

**Issue by syntaxerror13** [mjackson/resolve-pathname#45]
Hi, can you please add a licence file to the project? Also, am I correct assuming the project is under MIT licence just the file is missing? (package.json indicates MIT, that's why I think so)

**Comment by linde12** [comment]
@mjackson Can i help with this? resolve-pathname is an ancestral dependency which we would like to display a license for in our application.

Thanks

**Comment by r-tm** [comment]
Please add license file. We intend to use both resolve-pathname and value-equal commercially, but without legal risk.

**Comment by Eli-Black-Work** [comment]
We would also like to see this :)

**Comment by reverofevil** [comment]
@mjackson ping :)
